### ISSUE TITLE
Cannot read property 'htmlParse' of undefined

### ISSUE THREAD

**Issue by bingtsingw** [megalojs/megalo-vhtml-plugin#1]
发现`var octoParse = require('octoparse').default `引入的变量`octoParse`是`undefined`, 改成`var octoParse = require('octoparse')`才能正常引入, 我试了octoparse`^0.2.0`和`^0.3.0`版本, 都有这个问题

**Comment by elcarim5efil** [comment]
谢谢反馈，0.1.2 重新更换成 commonjs 的引用方式。

**Comment by bingtsingw** [comment]
谢谢这么快修复, 可以正常用了~
